### ISSUE TITLE
Add Prettier and/or .editorconfig for formatting

### ISSUE THREAD

**Issue by dylanirlbeck** [dylanirlbeck/tailwind-ppx#122]
We have a few JS files in the project with no associated formater/linter, so let's add one.

**Comment by JakubMarkiewicz** [comment]
Would just simple 
```json
{
    "trailingComma": "es5",
    "tabWidth": 4,
    "semi": false,
    "singleQuote": true
}
```
with ignoring
```sh
*.json
*.css
*.bs.js
*.yml
*.md
```
and workflow
```yml
      - name: format js files
        run: |
          npx prettier --write .
          git add "*.js"
```

Be fine for you? I'm not sure about the workflow, never used it before
